apiVersion: v1
kind: Pod
metadata:
 name: deephealth-uc4-pytorch-training-4gpu-noblackmasks
spec:
 restartPolicy: Never
 containers:
 - name: deephealth-uc4
   image: riccardorenzulli/deephealth-uc4:pytorch
   command: ["bash", "-c"]
   args: ["cd UC4_pipeline/pytorch/; python3 train.py --config config_noblackmasks.json"]
   volumeMounts:
          - name: download
            mountPath: /data
          - name: shm
            mountPath: /dev/shm
   env:
    - name: WANDB_BASE_URL
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: host
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: key
    - name: PYTHONUNBUFFERED
      value: "1"
   resources:
     limits:
       nvidia.com/gpu: 4
     requests:
       nvidia.com/gpu: 4
 volumes:
      - name: download
        persistentVolumeClaim:
          claimName: unitochest
      - name: shm
        emptyDir:
          medium: Memory
