apiVersion: v1
kind: Pod
metadata:
 name: deephealth-uc4-eddl-processed
spec:
 restartPolicy: Never
 containers:
 - name: deephealth-uc4
   image: riccardorenzulli/deephealth-uc4:eddl-dataset
   command: ["bash", "-c"]
   args: ["cd UC4_pipeline/eddl/src; python3 processed_data.py --input_path /data/deephealth/deephealth-uc4/data/interim/unitochest --output_path /data/deephealth/deephealth-uc4/data/eddl/processed/unitochest_noblackmasks"]
   volumeMounts:
          - name: download
            mountPath: /data
   env:
    - name: WANDB_BASE_URL
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: host
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: key
   resources:
     limits:
       nvidia.com/gpu: 1
     requests:
       nvidia.com/gpu: 1
 volumes:
      - name: download
        persistentVolumeClaim:
          claimName: unitochest
