apiVersion: v1
kind: Pod
metadata:
 name: deephealth-uc4-test-1gpu
spec:
 restartPolicy: Never
 containers:
 - name: deephealth-uc4
   image: riccardorenzulli/deephealth-uc4:cudnn
   command: ["bash", "-c"]
   args: ["cd UC4_pipeline/eddl/src; python3 test_model.py --dataset /data/deephealth/deephealth-uc4/data/eddl/processed/unitochest_98/dataset_molinette.yml --ckpts dh-uc4_epoch_2_miou_0.5861243425093038.bin --wb_run_path eidoslab/deephealth-uc4/2iwcvn0o --batch_size 1 --gpu 1 --num_workers 1 --queue_ratio_size 4"]
   volumeMounts:
          - name: download
            mountPath: /data
   env:
    - name: WANDB_BASE_URL
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: host
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: key
   resources:
     limits:
       nvidia.com/gpu: 1
     requests:
       nvidia.com/gpu: 1
 volumes:
      - name: download
        persistentVolumeClaim:
          claimName: deephealth-uc4
