apiVersion: v1
kind: Pod
metadata:
 name: sleep-unitochest
spec:
 restartPolicy: Never
 containers:
 - name: sleep
   image: riccardorenzulli/deephealth-uc4:pyecvl-pyeddl
   command: ["/bin/bash", "-c", "--"]
   args: ["while true; do sleep 30; done;"]
   volumeMounts:
          - name: download
            mountPath: /data
   env:
    - name: WANDB_BASE_URL
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: host
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: perlo-wandb-auth
          key: key
 volumes:
      - name: download
        persistentVolumeClaim:
          claimName: unitochest

