apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: deephealth-uc4
spec:
    storageClassName: cdk-cinder
    accessModes:
        - ReadWriteMany
    resources:
        requests:
          storage: 500Gi
